const {createClient}=window.supabase;
const supabase=createClient(window.VIBENEST_CONFIG.supabaseUrl,window.VIBENEST_CONFIG.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let session=null,currentProfile=null,currentNav="feed",authMode="login",toastTimer;

const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function toast(msg){const e=$("#toast");e.textContent=msg;e.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove("show"),3200)}
function authErrorMessage(error){const code=error?.code||error?.name||"";const msg=error?.message||"Error desconocido.";if(code==="invalid_credentials")return"Correo o contraseña incorrectos.";if(code==="email_not_confirmed")return"Este correo todavía no está confirmado.";if(code==="user_already_exists")return"Ya existe una cuenta con ese correo.";if(code==="weak_password")return"La contraseña no cumple los requisitos.";if(code==="over_email_send_rate_limit")return"Demasiados intentos. Espera un momento.";if(code==="email_provider_disabled")return"El acceso por correo está desactivado en Supabase.";return msg}
function showAuthError(error){console.error("VibeNest Auth:",error);toast(authErrorMessage(error))}

function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function avatar(p,small=false){return p?.avatar_url?'<img class="avatar '+(small?"small":"")+'" src="'+esc(p.avatar_url)+'" alt="">':'<div class="avatar '+(small?"small":"")+'">'+esc((p?.display_name||p?.username||"?").slice(0,1).toUpperCase())+'</div>'}
function timeAgo(d){const n=Math.floor((Date.now()-new Date(d))/1000);if(n<60)return"ahora";if(n<3600)return Math.floor(n/60)+" min";if(n<86400)return Math.floor(n/3600)+" h";return new Date(d).toLocaleDateString("es-CR",{day:"numeric",month:"short"})}
async function profileById(id){const {data,error}=await supabase.from("profiles").select("*").eq("id",id).maybeSingle();if(error)throw error;return data}
async function boot(){
  try{
    const {data,error}=await supabase.auth.getSession();
    if(error){showAuthError(error);return}
    await handleSession(data.session);
    supabase.auth.onAuthStateChange((_e,s)=>{handleSession(s).catch(err=>showAuthError(err))});
  }catch(err){showAuthError(err)}
}
async function handleSession(s){
  session=s;
  if(!s){currentProfile=null;$("#authView").classList.remove("hidden");$("#appView").classList.add("hidden");return}
  currentProfile=await profileById(s.user.id);if(!currentProfile){const pending=JSON.parse(localStorage.getItem("vibenest_pending_profile")||"null");const base=(s.user.email||"user").split("@")[0].replace(/[^A-Za-z0-9_]/g,"").slice(0,18)||"user";const username=(pending?.email===s.user.email&&pending.username)?pending.username:base+"_"+Math.floor(Math.random()*999);const displayName=(pending?.email===s.user.email&&pending.displayName)?pending.displayName:base;const p=await supabase.from("profiles").insert({id:s.user.id,username,display_name:displayName});if(p.error&&p.error.code==="23505"){await supabase.from("profiles").insert({id:s.user.id,username:base+"_"+Math.floor(Math.random()*999),display_name:displayName})}localStorage.removeItem("vibenest_pending_profile");currentProfile=await profileById(s.user.id)}$("#authView").classList.add("hidden");$("#appView").classList.remove("hidden");renderMini();navigate(currentNav)}
function renderMini(){$("#miniProfile").innerHTML='<div style="display:flex;gap:9px;align-items:center;padding:8px 6px 13px">'+avatar(currentProfile,true)+'<div><b>'+esc(currentProfile?.display_name)+'</b><small class="muted">@'+esc(currentProfile?.username)+'</small></div></div>'}
async function navigate(n){currentNav=n;$$("[data-nav]").forEach(b=>b.classList.toggle("active",b.dataset.nav===n));if(n==="feed")renderFeed();if(n==="profile")renderProfile(currentProfile.id);if(n==="notifications")renderNotifications()}
function composer(){return'<div class="card composer"><div class="composer-head">'+avatar(currentProfile,true)+'<div><b>'+esc(currentProfile.display_name)+'</b><small class="muted"> · Comparte algo</small></div></div><textarea id="postText" maxlength="2000" placeholder="¿Qué estás pensando?"></textarea><div class="composer-actions"><label class="file-label">📎 Foto/video<input id="mediaInput" type="file" accept="image/*,video/*" hidden></label><button class="primary" id="postBtn">Publicar</button></div><small id="fileName" class="muted"></small></div>'}
async function renderFeed(){const c=$("#content");c.innerHTML=composer()+"<h3 class='feed-title'>Tu feed</h3><div id='feedList' class='loading'>Cargando publicaciones…</div>";bindComposer();const {data,error}=await supabase.from("posts").select("*").order("created_at",{ascending:false}).limit(50);if(error){toast(error.message);$("#feedList").innerHTML='<div class="empty">No se pudo cargar el feed.</div>';return}const ids=[...new Set((data||[]).map(x=>x.user_id))];let profiles=[];if(ids.length)profiles=(await supabase.from("profiles").select("*").in("id",ids)).data||[];const map=Object.fromEntries(profiles.map(p=>[p.id,p]));const {data:likes}=session?await supabase.from("likes").select("post_id").eq("user_id",session.user.id).in("post_id",(data||[]).map(x=>x.id).length?(data||[]).map(x=>x.id):["00000000-0000-0000-0000-000000000000"]):{data:[]};const liked=new Set((likes||[]).map(x=>x.post_id));const counts={};for(const p of data||[]){const r=await supabase.from("likes").select("post_id",{count:"exact",head:true}).eq("post_id",p.id);counts[p.id]=r.count||0}$("#feedList").innerHTML=(data||[]).map(p=>postHtml(p,map[p.user_id],liked.has(p.id),counts[p.id]||0)).join("")||'<div class="card empty">Todavía no hay publicaciones. ¡Sé el primero!</div>';bindPosts()}
function postHtml(p,u,liked,count){return'<article class="card post" data-post="'+p.id+'"><div class="post-head">'+avatar(u,true)+'<div><div class="post-user">'+esc(u?.display_name||"Usuario")+'</div><small class="muted">@'+esc(u?.username||"user")+' · '+timeAgo(p.created_at)+'</small></div></div>'+(p.content?'<div class="post-content">'+esc(p.content)+'</div>':"")+(p.media_url?(p.media_type==="video"?'<video class="post-media" controls src="'+esc(p.media_url)+'"></video>':'<img class="post-media" loading="lazy" src="'+esc(p.media_url)+'" alt="Publicación">'):"")+'<div class="post-actions"><button class="'+(liked?"liked":"")+'" data-like="'+p.id+'">♥ '+count+'</button><button data-comments="'+p.id+'">💬 Comentarios</button>'+(p.user_id===session.user.id?'<button data-delete="'+p.id+'">🗑</button>':'<button data-report="'+p.id+'">⚑</button>')+'</div><div class="comments" id="comments-'+p.id+'"></div></article>'}
function bindComposer(){$("#postBtn").onclick=createPost;$("#mediaInput").onchange=e=>$("#fileName").textContent=e.target.files[0]?.name||""}
async function createPost(){const text=$("#postText").value.trim(),file=$("#mediaInput").files[0];if(!text&&!file)return toast("Escribe algo o elige un archivo.");let media_url=null,media_type=null;if(file){if(file.size>25*1024*1024)return toast("El archivo supera 25 MB.");const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=session.user.id+"/"+crypto.randomUUID()+"-"+safeName;const up=await supabase.storage.from("media").upload(path,file,{upsert:false,contentType:file.type});if(up.error)return toast(up.error.message);media_url=supabase.storage.from("media").getPublicUrl(path).data.publicUrl;media_type=file.type.startsWith("video/")?"video":"image"}const {error}=await supabase.from("posts").insert({user_id:session.user.id,content:text||null,media_url,media_type,media_path:file?path:null});if(error){if(file)await supabase.storage.from("media").remove([path]);return toast(error.message);}toast("¡Publicado!");renderFeed()}
async function bindPosts(){const list=[...$$("[data-post]")];list.forEach(card=>{const id=card.dataset.post;card.querySelector("[data-like]")?.addEventListener("click",()=>toggleLike(id));card.querySelector("[data-comments]")?.addEventListener("click",()=>loadComments(id));card.querySelector("[data-delete]")?.addEventListener("click",()=>deletePost(id));card.querySelector("[data-report]")?.addEventListener("click",()=>reportPost(id))})}
async function toggleLike(id){const q=await supabase.from("likes").select("*").eq("post_id",id).eq("user_id",session.user.id).maybeSingle();if(q.error){toast(q.error.message);return}const r=q.data?await supabase.from("likes").delete().eq("post_id",id).eq("user_id",session.user.id):await supabase.from("likes").insert({post_id:id,user_id:session.user.id});if(r.error){toast(r.error.message);return}renderFeed()}
async function loadComments(id){const box=$("#comments-"+id);if(!box)return;const {data,error}=await supabase.from("comments").select("*").eq("post_id",id).order("created_at",{ascending:true});if(error){toast(error.message);return}const ids=[...new Set((data||[]).map(x=>x.user_id))];const ps=ids.length?(await supabase.from("profiles").select("*").in("id",ids)).data||[]:[];const m=Object.fromEntries(ps.map(p=>[p.id,p]));box.innerHTML=(data||[]).map(c=>'<div class="comment">'+avatar(m[c.user_id],true)+'<p><b>'+esc(m[c.user_id]?.display_name||"Usuario")+'</b><br>'+esc(c.content)+'</p></div>').join("")+'<form class="comment-form"><input maxlength="500" placeholder="Escribe un comentario…"><button>Enviar</button></form>';box.querySelector("form").onsubmit=async e=>{e.preventDefault();const v=e.target.querySelector("input").value.trim();if(!v)return;const r=await supabase.from("comments").insert({post_id:id,user_id:session.user.id,content:v});if(r.error)toast(r.error.message);else loadComments(id)}}
async function deletePost(id){
  if(!confirm("¿Eliminar esta publicación?"))return;
  const q=await supabase.from("posts").select("media_path").eq("id",id).eq("user_id",session.user.id).maybeSingle();
  const r=await supabase.from("posts").delete().eq("id",id).eq("user_id",session.user.id);
  if(r.error){toast(r.error.message);return}
  if(q.data?.media_path)await supabase.storage.from("media").remove([q.data.media_path]);
  renderFeed()
}
async function reportPost(id){
  const choice=prompt("Motivo: 1=spam, 2=acoso, 3=contenido inseguro, 4=suplantación, 5=otro");
  const reasons={1:"spam",2:"harassment",3:"unsafe",4:"impersonation",5:"other"};
  const reason=reasons[choice?.trim()];
  if(!reason)return toast("Elige un motivo del 1 al 5.");
  const r=await supabase.from("reports").insert({reporter_id:session.user.id,target_post_id:id,reason});
  toast(r.error?r.error.message:"Reporte enviado.")
}
async function renderProfile(id){const p=await profileById(id);if(!p)return;const [posts,followers,following,follow]=await Promise.all([supabase.from("posts").select("*").eq("user_id",id).order("created_at",{ascending:false}),supabase.from("follows").select("follower_id",{count:"exact",head:true}).eq("following_id",id),supabase.from("follows").select("following_id",{count:"exact",head:true}).eq("follower_id",id),id===session.user.id?{data:null}:supabase.from("follows").select("*").eq("follower_id",session.user.id).eq("following_id",id).maybeSingle()]);const mine=id===session.user.id;$("#content").innerHTML='<div class="card profile-head"><div class="profile-top">'+avatar(p)+'<div class="profile-info"><h2>'+esc(p.display_name)+'</h2><div class="muted">@'+esc(p.username)+'</div><p>'+esc(p.bio||"Sin biografía todavía.")+'</p></div><div class="profile-actions">'+(mine?'<button class="primary" id="editProfile">Editar perfil</button>':'<button class="primary" id="followBtn">'+(follow.data?"Dejar de seguir":"Seguir")+'</button>')+'</div></div><div class="stats"><span><b>'+(posts.data?.length||0)+'</b> publicaciones</span><span><b>'+(followers.count||0)+'</b> seguidores</span><span><b>'+(following.count||0)+'</b> siguiendo</span></div></div><div id="profilePosts"></div>';if(mine)$("#editProfile").onclick=editProfile;else $("#followBtn").onclick=()=>toggleFollow(id,!!follow.data);$("#profilePosts").innerHTML=(posts.data||[]).map(x=>postHtml(x,p,false,0)).join("")||'<div class="card empty">No hay publicaciones.</div>';bindPosts()}
async function toggleFollow(id,isFollowing){const r=isFollowing?await supabase.from("follows").delete().eq("follower_id",session.user.id).eq("following_id",id):await supabase.from("follows").insert({follower_id:session.user.id,following_id:id});if(r.error)toast(r.error.message);else{toast(isFollowing?"Dejaste de seguir.":"Ahora sigues a esta persona.");renderProfile(id)}}
function editProfile(){openModal('<h2>Editar perfil</h2><form id="editForm"><label>Nombre<input id="editName" maxlength="40" value="'+esc(currentProfile.display_name)+'"></label><label>Usuario<input id="editUser" maxlength="24" value="'+esc(currentProfile.username)+'"></label><label>Bio<textarea id="editBio" maxlength="160">'+esc(currentProfile.bio||"")+'</textarea></label><button class="primary wide">Guardar</button></form>');$("#editForm").onsubmit=async e=>{e.preventDefault();const u=$("#editUser").value.trim().toLowerCase();if(!/^[a-z0-9_]{3,24}$/.test(u))return toast("Usuario: 3-24 caracteres, letras, números o _.");const r=await supabase.from("profiles").update({display_name:$("#editName").value.trim(),username:u,bio:$("#editBio").value.trim()}).eq("id",session.user.id);if(r.error)toast(r.error.message);else{currentProfile=await profileById(session.user.id);renderMini();closeModal();renderProfile(session.user.id)}}}
async function renderNotifications(){const {data,error}=await supabase.from("notifications").select("*").eq("recipient_id",session.user.id).order("created_at",{ascending:false}).limit(50);if(error){toast(error.message);return}$("#content").innerHTML='<div class="card"><div style="padding:16px;border-bottom:1px solid var(--line)"><h2 style="margin:0">Notificaciones</h2></div><div id="notifs"></div></div>';const ids=[...new Set((data||[]).map(n=>n.actor_id).filter(Boolean))];const ps=ids.length?(await supabase.from("profiles").select("*").in("id",ids)).data||[]:[];const m=Object.fromEntries(ps.map(p=>[p.id,p]));$("#notifs").innerHTML=(data||[]).map(n=>'<div class="notification '+(!n.read?"unread":"")+'">'+avatar(m[n.actor_id],true)+'<div><b>'+esc(m[n.actor_id]?.display_name||"VibeNest")+'</b> '+esc(n.message||"tiene una actualización.")+'<small class="muted"> · '+timeAgo(n.created_at)+'</small></div></div>').join("")||'<div class="empty">No tienes notificaciones.</div>';await supabase.from("notifications").update({read:true}).eq("recipient_id",session.user.id).eq("read",false);$("#notifCount").textContent=""}
async function searchUsers(q){
  q=q.trim().replace(/[%,().]/g," ");
  if(!q)return;
  const {data,error}=await supabase.from("profiles").select("*").or("username.ilike.%"+q+"%,display_name.ilike.%"+q+"%").limit(20);
  if(error){toast(error.message);return}$("#content").innerHTML='<div class="card results"><h3>Resultados</h3>'+(data||[]).map(p=>'<div class="result">'+avatar(p,true)+'<div><b>'+esc(p.display_name)+'</b><small class="muted">@'+esc(p.username)+'</small></div><span class="spacer"></span><button class="primary" data-user="'+p.id+'">Ver</button></div>').join("")+'</div>';$$("[data-user]").forEach(b=>b.onclick=()=>renderProfile(b.dataset.user))}
function openModal(html){$("#modalContent").innerHTML=html;$("#modal").classList.remove("hidden")}function closeModal(){$("#modal").classList.add("hidden")}
function rules(){openModal('<h2>Reglas de VibeNest</h2><ol><li>Trata a las demás personas con respeto.</li><li>No publiques datos personales de otras personas.</li><li>No subas contenido ilegal, engañoso o que pueda poner a alguien en peligro.</li><li>Usa reportes y bloqueos cuando algo te incomode.</li><li>VibeNest es un proyecto web: mantén tus credenciales privadas.</li></ol>')}
$$("[data-auth]").forEach(b=>b.onclick=()=>{authMode=b.dataset.auth;$$("[data-auth]").forEach(x=>x.classList.toggle("active",x===b));$("#displayWrap").classList.toggle("hidden",authMode==="login");$("#usernameWrap").classList.toggle("hidden",authMode==="login");$("#authSubmit").textContent=authMode==="login"?"Entrar":"Crear cuenta"})
$("#authForm").onsubmit=async e=>{e.preventDefault();const email=$("#email").value.trim(),password=$("#password").value,username=$("#username").value.trim().toLowerCase(),displayName=$("#displayName").value.trim(),btn=$("#authSubmit");btn.disabled=true;btn.textContent=authMode==="login"?"Entrando…":"Creando…";try{if(authMode==="login"){const r=await supabase.auth.signInWithPassword({email,password});if(r.error){showAuthError(r.error);return}if(!r.data?.session){toast("Supabase no devolvió una sesión. Revisa la configuración de acceso.");return}await handleSession(r.data.session)}else{if(!/^[a-z0-9_]{3,24}$/.test(username))return toast("Usuario: 3-24 caracteres, letras, números o _.");const r=await supabase.auth.signUp({email,password,options:{data:{username,display_name:displayName||username},emailRedirectTo:window.location.origin}});if(r.error){showAuthError(r.error);return}if(r.data.user&&r.data.session){await handleSession(r.data.session);toast("¡Cuenta creada!")}else if(r.data.user){localStorage.setItem("vibenest_pending_profile",JSON.stringify({email,username,displayName:displayName||username}));toast("Cuenta creada. Revisa tu correo para confirmar la cuenta.");$("#authSubmit").textContent="Revisa tu correo"}}catch(err){console.error(err);toast(err?.message||"Ocurrió un error al iniciar sesión.")}finally{btn.disabled=false;btn.textContent=authMode==="login"?"Entrar":"Crear cuenta"}}
$("#logoutBtn").onclick=()=>supabase.auth.signOut();$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.vibeDark=document.body.classList.contains("dark")?"1":"0"};if(localStorage.vibeDark==="1")document.body.classList.add("dark");
$$("[data-nav]").forEach(b=>b.onclick=e=>{e.preventDefault();navigate(b.dataset.nav)});$("#rulesBtn").onclick=rules;$("#rulesBtn2").onclick=rules;$(".modal-close").onclick=closeModal;$("#modal").onclick=e=>{if(e.target.id==="modal")closeModal()};$("#searchInput").onkeydown=e=>{if(e.key==="Enter")searchUsers(e.target.value)};boot();